spring:
  application:
    name: jharkhand_project

  datasource:
    url: jdbc:postgresql://localhost:5432/jharkhand
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: redis-11259.c10.us-east-1-4.ec2.redns.redis-cloud.com
      port: 11259
      username: default
      password: SA2PnOGiBylYHcetMrDkg3cHauYxs13R
      timeout: 60000ms
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 100000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: thepeoplespress8@gmail.com
    password: wuiq jusn xjiz tcgy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8000
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: hoieihfor3gbndopejo9pprf3hoifeqoindoicnvoief90r3wiuwe
    expiration: 15552000000 # 6 months in ms (assuming 30 days per month)
    refresh-expiration: 31536000000 # 1 year in ms (assuming 365 days per year)

  otp:
    expiration: 300000 # 5 minutes in ms
    length: 6

  email:
    from: thepeoplespress8@gmail.com

cloudinary:
  cloud-name: ddaf68an1
  api-key: 146275744557721
  api-secret: 9rGysviAew0bEKMSjSHl0qmuulY

logging:
  level:
    com.jharkhand.news: DEBUG
    org.springframework.security: DEBUG
