spring:
  application:
    name: jharkhand_project

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SEC}
            scope:
              - openid
              - profile
              - email

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?currentSchema=public&TimeZone=Asia/Kolkata
    username: gen_user
    password: =+5E.S_l70xpHd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
        use_jdbc_metadata_defaults: false

  jackson:
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 14833
      username: default
      password: ${REDIS_PASS}
      timeout: 60000ms
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 100000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: updatesjharkhandbihar@gmail.com
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: ${JWT_SEC}
    expiration: 15552000000
    refresh-expiration: 31536000000

  otp:
    expiration: 300000
    length: 6

  email:
    from: updatesjharkhandbihar@gmail.com

cloudinary:
  cloud-name: duf6vxnbj
  api-key: 142139991245357
  api-secret: yDOSHiSDflYzaWXqGLvCrPJrSjU

logging:
  level:
    com.jharkhand.news: DEBUG
    org.springframework.security: DEBUG


onesignal:
  app:
    id: 8f6aeaec-1885-4245-b351-0885c4cb7312
  rest:
    api:
      key: os_v2_app_r5vov3ayqvbelm2rbcc4js3tcildv6g56vhuhbnvifdbdzpcff64j2n4e4asq5advnpuvwloauftpysjom2ncwvdha3nykewgoacu4a

