spring:
  application:
    name: jharkhand_project

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 208937376257-rkmkeicd91ltac7qgpuefk1ikkus552g.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email

  datasource:
    url: jdbc:postgresql://localhost:5432/jharkhand?currentSchema=public&timeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
        use_jdbc_metadata_defaults: false

  jackson:
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: redis-17738.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
      port: 17738
      username: default
      password: FkxxCWO3fSrI80LagaGUMEpO8aHOQV6y
      timeout: 60000ms
      database: 0

  cache:
    type: redis
    redis:
      time-to-live: 100000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: thepeoplespress8@gmail.com
    password: wuiq jusn xjiz tcgy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8000
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: hoieihfor3gbndopejo9pprf3hoifeqoindoicnvoief90r3wiuwe
    expiration: 15552000000 # 6 months in ms (assuming 30 days per month)
    refresh-expiration: 31536000000 # 1 year in ms (assuming 365 days per year)

  otp:
    expiration: 300000 # 5 minutes in ms
    length: 6

  email:
    from: thepeoplespress8@gmail.com

cloudinary:
  cloud-name: duf6vxnbj
  api-key: 142139991245357
  api-secret: yDOSHiSDflYzaWXqGLvCrPJrSjU

logging:
  level:
    com.jharkhand.news: DEBUG
    org.springframework.security: DEBUG
